services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fastapi_blog_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports: [ "9000:9000", "9001:9001" ]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./_data/minio:/data

  minio-setup:
    image: minio/mc:latest
    depends_on: [ minio ]
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/blog-images || true &&
      mc anonymous set public local/blog-images || true
      "

  worker:
    build: .
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
    command: >
      poetry run celery -A src.app.celery_app.celery worker --loglevel=INFO

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build: .
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+psycopg://fastapi_user:fastapi_password@db:5432/fastapi_blog_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//
    ports:
      - "8000:8000"
    command: >
      poetry run uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'

volumes:
  db_data:
