name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: "true"
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
      POETRY_NO_INTERACTION: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install "poetry==2.1.3"

      - name: Show Poetry version and config
        run: |
          poetry --version
          poetry config --list | grep virtualenvs

      - name: Install deps
        run: |
          poetry install --no-root

      - name: Lint (ruff)
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Pre-commit (sanity checks)
        run: poetry run pre-commit run --all-files

      - name: Tests
        run: poetry run pytest -q
